/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package knightstour;

import java.awt.Button;

/**
 *
 * @author PREOATOR
 */
public class AnswerPrinting extends javax.swing.JFrame {

    /**
     * Creates new form AnswerPrinting
     */
    private int[][] table=new int[8][8];
    private int counter=1;
    
    public AnswerPrinting(int[][] d) {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        table=d;
        this.printChessTable(d);
        tryToPrint();
    }
     private void printChessTable(int[][] d) {
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                System.out.print("\t" + d[i][j]);
            }
            System.out.println();
        }
        System.out.println("   --------------------------------------------------------------------");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        WelcomeText = new javax.swing.JLabel();
        MainLogo5 = new javax.swing.JLabel();
        MainLogo7 = new javax.swing.JLabel();
        MainLogo8 = new javax.swing.JLabel();
        MainLogo6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();
        button12 = new java.awt.Button();
        button13 = new java.awt.Button();
        button14 = new java.awt.Button();
        button15 = new java.awt.Button();
        button16 = new java.awt.Button();
        button17 = new java.awt.Button();
        button18 = new java.awt.Button();
        button19 = new java.awt.Button();
        button20 = new java.awt.Button();
        button21 = new java.awt.Button();
        button22 = new java.awt.Button();
        button23 = new java.awt.Button();
        button24 = new java.awt.Button();
        button25 = new java.awt.Button();
        button26 = new java.awt.Button();
        button27 = new java.awt.Button();
        button28 = new java.awt.Button();
        button29 = new java.awt.Button();
        button30 = new java.awt.Button();
        button31 = new java.awt.Button();
        button32 = new java.awt.Button();
        button33 = new java.awt.Button();
        button34 = new java.awt.Button();
        button35 = new java.awt.Button();
        button36 = new java.awt.Button();
        button37 = new java.awt.Button();
        button38 = new java.awt.Button();
        button39 = new java.awt.Button();
        button40 = new java.awt.Button();
        button41 = new java.awt.Button();
        button42 = new java.awt.Button();
        button43 = new java.awt.Button();
        button44 = new java.awt.Button();
        button45 = new java.awt.Button();
        button46 = new java.awt.Button();
        button47 = new java.awt.Button();
        button48 = new java.awt.Button();
        button49 = new java.awt.Button();
        button50 = new java.awt.Button();
        button51 = new java.awt.Button();
        button52 = new java.awt.Button();
        button53 = new java.awt.Button();
        button54 = new java.awt.Button();
        button55 = new java.awt.Button();
        button56 = new java.awt.Button();
        button57 = new java.awt.Button();
        button58 = new java.awt.Button();
        button59 = new java.awt.Button();
        button60 = new java.awt.Button();
        button61 = new java.awt.Button();
        button62 = new java.awt.Button();
        button63 = new java.awt.Button();
        button64 = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("<");
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 50, 30));

        jButton2.setText(">");
        jButton2.setToolTipText("");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 50, 30));

        jButton3.setText(">>");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 50, 30));

        jButton4.setText("<<");
        jButton4.setEnabled(false);
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 50, 30));

        jButton5.setText("RESET");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 200, -1));

        jLabel1.setText("Step 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, 30));

        Header.setBackground(new java.awt.Color(37, 38, 103));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        WelcomeText.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(WelcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 20, 40));

        MainLogo5.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo5.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(MainLogo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 20, 20));

        MainLogo7.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo7.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(MainLogo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 20, 20));

        MainLogo8.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo8.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(MainLogo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 20, 20));

        MainLogo6.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo6.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(MainLogo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 280, 20));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 8)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("About");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("© 2018 Knight's Tour Solver, All rights reserved.");
        Header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 30));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 480, 30));

        button1.setBackground(new java.awt.Color(255, 255, 255));
        button1.setEnabled(false);
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setPreferredSize(new java.awt.Dimension(40, 40));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        button1.getAccessibleContext().setAccessibleName("A8");

        button2.setBackground(new java.awt.Color(37, 38, 103));
        button2.setEnabled(false);
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));
        button2.getAccessibleContext().setAccessibleName("B8");

        button3.setBackground(new java.awt.Color(255, 255, 255));
        button3.setEnabled(false);
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setPreferredSize(new java.awt.Dimension(40, 40));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        button4.setBackground(new java.awt.Color(37, 38, 103));
        button4.setEnabled(false);
        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setPreferredSize(new java.awt.Dimension(40, 40));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        button5.setBackground(new java.awt.Color(255, 255, 255));
        button5.setEnabled(false);
        button5.setForeground(new java.awt.Color(255, 255, 255));
        button5.setPreferredSize(new java.awt.Dimension(40, 40));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        button6.setBackground(new java.awt.Color(37, 38, 103));
        button6.setEnabled(false);
        button6.setForeground(new java.awt.Color(255, 255, 255));
        button6.setPreferredSize(new java.awt.Dimension(40, 40));
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        getContentPane().add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        button7.setBackground(new java.awt.Color(255, 255, 255));
        button7.setEnabled(false);
        button7.setForeground(new java.awt.Color(255, 255, 255));
        button7.setPreferredSize(new java.awt.Dimension(40, 40));
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        getContentPane().add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        button8.setBackground(new java.awt.Color(37, 38, 103));
        button8.setEnabled(false);
        button8.setForeground(new java.awt.Color(255, 255, 255));
        button8.setPreferredSize(new java.awt.Dimension(40, 40));
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        getContentPane().add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        button9.setBackground(new java.awt.Color(37, 38, 103));
        button9.setEnabled(false);
        button9.setForeground(new java.awt.Color(255, 255, 255));
        button9.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        button10.setBackground(new java.awt.Color(255, 255, 255));
        button10.setEnabled(false);
        button10.setForeground(new java.awt.Color(255, 255, 255));
        button10.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        button11.setBackground(new java.awt.Color(37, 38, 103));
        button11.setEnabled(false);
        button11.setForeground(new java.awt.Color(255, 255, 255));
        button11.setPreferredSize(new java.awt.Dimension(40, 40));
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        getContentPane().add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        button12.setBackground(new java.awt.Color(255, 255, 255));
        button12.setEnabled(false);
        button12.setForeground(new java.awt.Color(255, 255, 255));
        button12.setPreferredSize(new java.awt.Dimension(40, 40));
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        getContentPane().add(button12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        button13.setBackground(new java.awt.Color(37, 38, 103));
        button13.setEnabled(false);
        button13.setForeground(new java.awt.Color(255, 255, 255));
        button13.setPreferredSize(new java.awt.Dimension(40, 40));
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });
        getContentPane().add(button13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        button14.setBackground(new java.awt.Color(255, 255, 255));
        button14.setEnabled(false);
        button14.setForeground(new java.awt.Color(255, 255, 255));
        button14.setPreferredSize(new java.awt.Dimension(40, 40));
        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });
        getContentPane().add(button14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        button15.setBackground(new java.awt.Color(37, 38, 103));
        button15.setEnabled(false);
        button15.setForeground(new java.awt.Color(255, 255, 255));
        button15.setPreferredSize(new java.awt.Dimension(40, 40));
        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });
        getContentPane().add(button15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        button16.setBackground(new java.awt.Color(255, 255, 255));
        button16.setEnabled(false);
        button16.setForeground(new java.awt.Color(255, 255, 255));
        button16.setPreferredSize(new java.awt.Dimension(40, 40));
        button16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button16ActionPerformed(evt);
            }
        });
        getContentPane().add(button16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        button17.setBackground(new java.awt.Color(255, 255, 255));
        button17.setEnabled(false);
        button17.setForeground(new java.awt.Color(255, 255, 255));
        button17.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        button18.setBackground(new java.awt.Color(37, 38, 103));
        button18.setEnabled(false);
        button18.setForeground(new java.awt.Color(255, 255, 255));
        button18.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        button19.setBackground(new java.awt.Color(255, 255, 255));
        button19.setEnabled(false);
        button19.setForeground(new java.awt.Color(255, 255, 255));
        button19.setPreferredSize(new java.awt.Dimension(40, 40));
        button19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button19ActionPerformed(evt);
            }
        });
        getContentPane().add(button19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        button20.setBackground(new java.awt.Color(37, 38, 103));
        button20.setEnabled(false);
        button20.setForeground(new java.awt.Color(255, 255, 255));
        button20.setPreferredSize(new java.awt.Dimension(40, 40));
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });
        getContentPane().add(button20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        button21.setBackground(new java.awt.Color(255, 255, 255));
        button21.setEnabled(false);
        button21.setForeground(new java.awt.Color(255, 255, 255));
        button21.setPreferredSize(new java.awt.Dimension(40, 40));
        button21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button21ActionPerformed(evt);
            }
        });
        getContentPane().add(button21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        button22.setBackground(new java.awt.Color(37, 38, 103));
        button22.setEnabled(false);
        button22.setForeground(new java.awt.Color(255, 255, 255));
        button22.setPreferredSize(new java.awt.Dimension(40, 40));
        button22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button22ActionPerformed(evt);
            }
        });
        getContentPane().add(button22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        button23.setBackground(new java.awt.Color(255, 255, 255));
        button23.setEnabled(false);
        button23.setForeground(new java.awt.Color(255, 255, 255));
        button23.setPreferredSize(new java.awt.Dimension(40, 40));
        button23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button23ActionPerformed(evt);
            }
        });
        getContentPane().add(button23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        button24.setBackground(new java.awt.Color(37, 38, 103));
        button24.setEnabled(false);
        button24.setForeground(new java.awt.Color(255, 255, 255));
        button24.setPreferredSize(new java.awt.Dimension(40, 40));
        button24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button24ActionPerformed(evt);
            }
        });
        getContentPane().add(button24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        button25.setBackground(new java.awt.Color(37, 38, 103));
        button25.setEnabled(false);
        button25.setForeground(new java.awt.Color(255, 255, 255));
        button25.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        button26.setBackground(new java.awt.Color(255, 255, 255));
        button26.setEnabled(false);
        button26.setForeground(new java.awt.Color(255, 255, 255));
        button26.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        button27.setBackground(new java.awt.Color(37, 38, 103));
        button27.setEnabled(false);
        button27.setForeground(new java.awt.Color(255, 255, 255));
        button27.setPreferredSize(new java.awt.Dimension(40, 40));
        button27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button27ActionPerformed(evt);
            }
        });
        getContentPane().add(button27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        button28.setBackground(new java.awt.Color(255, 255, 255));
        button28.setEnabled(false);
        button28.setForeground(new java.awt.Color(255, 255, 255));
        button28.setPreferredSize(new java.awt.Dimension(40, 40));
        button28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button28ActionPerformed(evt);
            }
        });
        getContentPane().add(button28, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        button29.setBackground(new java.awt.Color(37, 38, 103));
        button29.setEnabled(false);
        button29.setForeground(new java.awt.Color(255, 255, 255));
        button29.setPreferredSize(new java.awt.Dimension(40, 40));
        button29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button29ActionPerformed(evt);
            }
        });
        getContentPane().add(button29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        button30.setBackground(new java.awt.Color(255, 255, 255));
        button30.setEnabled(false);
        button30.setForeground(new java.awt.Color(255, 255, 255));
        button30.setPreferredSize(new java.awt.Dimension(40, 40));
        button30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button30ActionPerformed(evt);
            }
        });
        getContentPane().add(button30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        button31.setBackground(new java.awt.Color(37, 38, 103));
        button31.setEnabled(false);
        button31.setForeground(new java.awt.Color(255, 255, 255));
        button31.setPreferredSize(new java.awt.Dimension(40, 40));
        button31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button31ActionPerformed(evt);
            }
        });
        getContentPane().add(button31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        button32.setBackground(new java.awt.Color(255, 255, 255));
        button32.setEnabled(false);
        button32.setForeground(new java.awt.Color(255, 255, 255));
        button32.setPreferredSize(new java.awt.Dimension(40, 40));
        button32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button32ActionPerformed(evt);
            }
        });
        getContentPane().add(button32, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        button33.setBackground(new java.awt.Color(255, 255, 255));
        button33.setEnabled(false);
        button33.setForeground(new java.awt.Color(255, 255, 255));
        button33.setPreferredSize(new java.awt.Dimension(40, 40));
        button33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button33ActionPerformed(evt);
            }
        });
        getContentPane().add(button33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        button34.setBackground(new java.awt.Color(37, 38, 103));
        button34.setEnabled(false);
        button34.setForeground(new java.awt.Color(255, 255, 255));
        button34.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        button35.setBackground(new java.awt.Color(255, 255, 255));
        button35.setEnabled(false);
        button35.setForeground(new java.awt.Color(255, 255, 255));
        button35.setPreferredSize(new java.awt.Dimension(40, 40));
        button35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button35ActionPerformed(evt);
            }
        });
        getContentPane().add(button35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        button36.setBackground(new java.awt.Color(37, 38, 103));
        button36.setEnabled(false);
        button36.setForeground(new java.awt.Color(255, 255, 255));
        button36.setPreferredSize(new java.awt.Dimension(40, 40));
        button36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button36ActionPerformed(evt);
            }
        });
        getContentPane().add(button36, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        button37.setBackground(new java.awt.Color(255, 255, 255));
        button37.setEnabled(false);
        button37.setForeground(new java.awt.Color(255, 255, 255));
        button37.setPreferredSize(new java.awt.Dimension(40, 40));
        button37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button37ActionPerformed(evt);
            }
        });
        getContentPane().add(button37, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        button38.setBackground(new java.awt.Color(37, 38, 103));
        button38.setEnabled(false);
        button38.setForeground(new java.awt.Color(255, 255, 255));
        button38.setPreferredSize(new java.awt.Dimension(40, 40));
        button38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button38ActionPerformed(evt);
            }
        });
        getContentPane().add(button38, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        button39.setBackground(new java.awt.Color(255, 255, 255));
        button39.setEnabled(false);
        button39.setForeground(new java.awt.Color(255, 255, 255));
        button39.setPreferredSize(new java.awt.Dimension(40, 40));
        button39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button39ActionPerformed(evt);
            }
        });
        getContentPane().add(button39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        button40.setBackground(new java.awt.Color(37, 38, 103));
        button40.setEnabled(false);
        button40.setForeground(new java.awt.Color(255, 255, 255));
        button40.setPreferredSize(new java.awt.Dimension(40, 40));
        button40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button40ActionPerformed(evt);
            }
        });
        getContentPane().add(button40, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        button41.setBackground(new java.awt.Color(37, 38, 103));
        button41.setEnabled(false);
        button41.setForeground(new java.awt.Color(255, 255, 255));
        button41.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button41, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        button42.setBackground(new java.awt.Color(255, 255, 255));
        button42.setEnabled(false);
        button42.setForeground(new java.awt.Color(255, 255, 255));
        button42.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button42, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        button43.setBackground(new java.awt.Color(37, 38, 103));
        button43.setEnabled(false);
        button43.setForeground(new java.awt.Color(255, 255, 255));
        button43.setPreferredSize(new java.awt.Dimension(40, 40));
        button43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button43ActionPerformed(evt);
            }
        });
        getContentPane().add(button43, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        button44.setBackground(new java.awt.Color(255, 255, 255));
        button44.setEnabled(false);
        button44.setForeground(new java.awt.Color(255, 255, 255));
        button44.setPreferredSize(new java.awt.Dimension(40, 40));
        button44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button44ActionPerformed(evt);
            }
        });
        getContentPane().add(button44, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        button45.setBackground(new java.awt.Color(37, 38, 103));
        button45.setEnabled(false);
        button45.setForeground(new java.awt.Color(255, 255, 255));
        button45.setPreferredSize(new java.awt.Dimension(40, 40));
        button45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button45ActionPerformed(evt);
            }
        });
        getContentPane().add(button45, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        button46.setBackground(new java.awt.Color(255, 255, 255));
        button46.setEnabled(false);
        button46.setForeground(new java.awt.Color(255, 255, 255));
        button46.setPreferredSize(new java.awt.Dimension(40, 40));
        button46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button46ActionPerformed(evt);
            }
        });
        getContentPane().add(button46, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        button47.setBackground(new java.awt.Color(37, 38, 103));
        button47.setEnabled(false);
        button47.setForeground(new java.awt.Color(255, 255, 255));
        button47.setPreferredSize(new java.awt.Dimension(40, 40));
        button47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button47ActionPerformed(evt);
            }
        });
        getContentPane().add(button47, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        button48.setBackground(new java.awt.Color(255, 255, 255));
        button48.setEnabled(false);
        button48.setForeground(new java.awt.Color(255, 255, 255));
        button48.setPreferredSize(new java.awt.Dimension(40, 40));
        button48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button48ActionPerformed(evt);
            }
        });
        getContentPane().add(button48, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        button49.setBackground(new java.awt.Color(255, 255, 255));
        button49.setEnabled(false);
        button49.setForeground(new java.awt.Color(255, 255, 255));
        button49.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button49, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        button50.setBackground(new java.awt.Color(37, 38, 103));
        button50.setEnabled(false);
        button50.setForeground(new java.awt.Color(255, 255, 255));
        button50.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button50, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        button51.setBackground(new java.awt.Color(255, 255, 255));
        button51.setEnabled(false);
        button51.setForeground(new java.awt.Color(255, 255, 255));
        button51.setPreferredSize(new java.awt.Dimension(40, 40));
        button51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button51ActionPerformed(evt);
            }
        });
        getContentPane().add(button51, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        button52.setBackground(new java.awt.Color(37, 38, 103));
        button52.setEnabled(false);
        button52.setForeground(new java.awt.Color(255, 255, 255));
        button52.setPreferredSize(new java.awt.Dimension(40, 40));
        button52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button52ActionPerformed(evt);
            }
        });
        getContentPane().add(button52, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        button53.setBackground(new java.awt.Color(255, 255, 255));
        button53.setEnabled(false);
        button53.setForeground(new java.awt.Color(255, 255, 255));
        button53.setPreferredSize(new java.awt.Dimension(40, 40));
        button53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button53ActionPerformed(evt);
            }
        });
        getContentPane().add(button53, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        button54.setBackground(new java.awt.Color(37, 38, 103));
        button54.setEnabled(false);
        button54.setForeground(new java.awt.Color(255, 255, 255));
        button54.setPreferredSize(new java.awt.Dimension(40, 40));
        button54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button54ActionPerformed(evt);
            }
        });
        getContentPane().add(button54, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        button55.setBackground(new java.awt.Color(255, 255, 255));
        button55.setEnabled(false);
        button55.setForeground(new java.awt.Color(255, 255, 255));
        button55.setPreferredSize(new java.awt.Dimension(40, 40));
        button55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button55ActionPerformed(evt);
            }
        });
        getContentPane().add(button55, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        button56.setBackground(new java.awt.Color(37, 38, 103));
        button56.setEnabled(false);
        button56.setForeground(new java.awt.Color(255, 255, 255));
        button56.setPreferredSize(new java.awt.Dimension(40, 40));
        button56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button56ActionPerformed(evt);
            }
        });
        getContentPane().add(button56, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        button57.setBackground(new java.awt.Color(37, 38, 103));
        button57.setEnabled(false);
        button57.setForeground(new java.awt.Color(255, 255, 255));
        button57.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button57, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        button58.setBackground(new java.awt.Color(255, 255, 255));
        button58.setEnabled(false);
        button58.setForeground(new java.awt.Color(255, 255, 255));
        button58.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(button58, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        button59.setBackground(new java.awt.Color(37, 38, 103));
        button59.setEnabled(false);
        button59.setForeground(new java.awt.Color(255, 255, 255));
        button59.setPreferredSize(new java.awt.Dimension(40, 40));
        button59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button59ActionPerformed(evt);
            }
        });
        getContentPane().add(button59, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        button60.setBackground(new java.awt.Color(255, 255, 255));
        button60.setEnabled(false);
        button60.setForeground(new java.awt.Color(255, 255, 255));
        button60.setPreferredSize(new java.awt.Dimension(40, 40));
        button60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button60ActionPerformed(evt);
            }
        });
        getContentPane().add(button60, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        button61.setBackground(new java.awt.Color(37, 38, 103));
        button61.setEnabled(false);
        button61.setForeground(new java.awt.Color(255, 255, 255));
        button61.setPreferredSize(new java.awt.Dimension(40, 40));
        button61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button61ActionPerformed(evt);
            }
        });
        getContentPane().add(button61, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, -1));

        button62.setBackground(new java.awt.Color(255, 255, 255));
        button62.setEnabled(false);
        button62.setForeground(new java.awt.Color(255, 255, 255));
        button62.setPreferredSize(new java.awt.Dimension(40, 40));
        button62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button62ActionPerformed(evt);
            }
        });
        getContentPane().add(button62, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        button63.setBackground(new java.awt.Color(37, 38, 103));
        button63.setEnabled(false);
        button63.setForeground(new java.awt.Color(255, 255, 255));
        button63.setPreferredSize(new java.awt.Dimension(40, 40));
        button63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button63ActionPerformed(evt);
            }
        });
        getContentPane().add(button63, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));

        button64.setBackground(new java.awt.Color(255, 255, 255));
        button64.setEnabled(false);
        button64.setForeground(new java.awt.Color(255, 255, 255));
        button64.setPreferredSize(new java.awt.Dimension(40, 40));
        button64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button64ActionPerformed(evt);
            }
        });
        getContentPane().add(button64, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/knightstour/table.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 420, 430));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/knightstour/header.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 140, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void tryToPrint(){
        Button[] b={button1,button2,button3,button4,button5,button6,button7,button8,button9,button10,button11,button12,button13,button14,button15,button16,button17,button18,button19,
            button20,button21,button22,button23,button24,button25,button26,button27,button28,button29,button30,button31,button32,button33,button34,button35,button36,button37,button38,button39,button40
            ,button41,button42,button43,button44,button45,button46,button47,button48,button49,button50,button51,button52,button53,button54,button55,button56,button57,button58,button59,button60,button61,button62,button63,button64};
        int i,j;
        for(i=0;i<8;i++){
            for(j=0;j<8;j++){
                if(table[i][j]<=counter){
                    b[(i*8)+j].setLabel(String.valueOf(table[i][j]));
                }else if(table[i][j]==counter){
                    b[(i*8)+j].setLabel("X");
                }else{
                    b[(i*8)+j].setLabel("");
                }
            }
        }
        /*if(table[0][0]<counter){button1.setLabel(String.valueOf(table[0][0]));}else if(table[0][0]==counter){button1.setLabel("X");}else{button1.setLabel("");}*/
    }
    
    
    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button8ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button11ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button12ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button13ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button14ActionPerformed

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button15ActionPerformed

    private void button16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button16ActionPerformed

    private void button19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button19ActionPerformed

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button20ActionPerformed

    private void button21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button21ActionPerformed

    private void button22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button22ActionPerformed

    private void button23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button23ActionPerformed

    private void button24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button24ActionPerformed

    private void button27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button27ActionPerformed

    private void button28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button28ActionPerformed

    private void button29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button29ActionPerformed

    private void button30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button30ActionPerformed

    private void button31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button31ActionPerformed

    private void button32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button32ActionPerformed

    private void button35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button35ActionPerformed

    private void button36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button36ActionPerformed

    private void button37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button37ActionPerformed

    private void button38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button38ActionPerformed

    private void button39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button39ActionPerformed

    private void button40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button40ActionPerformed

    private void button43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button43ActionPerformed

    private void button44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button44ActionPerformed

    private void button45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button45ActionPerformed

    private void button46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button46ActionPerformed

    private void button47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button47ActionPerformed

    private void button48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button48ActionPerformed

    private void button51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button51ActionPerformed

    private void button52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button52ActionPerformed

    private void button53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button53ActionPerformed

    private void button54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button54ActionPerformed

    private void button55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button55ActionPerformed

    private void button56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button56ActionPerformed

    private void button59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button59ActionPerformed

    private void button60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button60ActionPerformed

    private void button61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button61ActionPerformed

    private void button62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button62ActionPerformed

    private void button63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button63ActionPerformed

    private void button64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button64ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(counter+1<=64){
            jButton1.setEnabled(true);
            jButton4.setEnabled(true);
            counter++;
            jLabel1.setText("Step "+counter);
            tryToPrint();
        }
        if(counter==64)
        {
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(counter-1>=1){
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            counter--;
            jLabel1.setText("Step "+counter);
            tryToPrint();
        }
        if(counter==1)
        {
            jButton1.setEnabled(false);
            jButton4.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button33ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        counter=64;
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton1.setEnabled(true);
        jButton4.setEnabled(true);
        jLabel1.setText("Step "+counter);
        tryToPrint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        counter=1;
        jButton1.setEnabled(false);
        jButton4.setEnabled(false);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jLabel1.setText("Step "+counter);
        tryToPrint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        Table t=new Table();
        t.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new About().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnswerPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnswerPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnswerPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnswerPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnswerPrinting(null).setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel MainLogo5;
    private javax.swing.JLabel MainLogo6;
    private javax.swing.JLabel MainLogo7;
    private javax.swing.JLabel MainLogo8;
    private javax.swing.JLabel WelcomeText;
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button button14;
    private java.awt.Button button15;
    private java.awt.Button button16;
    private java.awt.Button button17;
    private java.awt.Button button18;
    private java.awt.Button button19;
    private java.awt.Button button2;
    private java.awt.Button button20;
    private java.awt.Button button21;
    private java.awt.Button button22;
    private java.awt.Button button23;
    private java.awt.Button button24;
    private java.awt.Button button25;
    private java.awt.Button button26;
    private java.awt.Button button27;
    private java.awt.Button button28;
    private java.awt.Button button29;
    private java.awt.Button button3;
    private java.awt.Button button30;
    private java.awt.Button button31;
    private java.awt.Button button32;
    private java.awt.Button button33;
    private java.awt.Button button34;
    private java.awt.Button button35;
    private java.awt.Button button36;
    private java.awt.Button button37;
    private java.awt.Button button38;
    private java.awt.Button button39;
    private java.awt.Button button4;
    private java.awt.Button button40;
    private java.awt.Button button41;
    private java.awt.Button button42;
    private java.awt.Button button43;
    private java.awt.Button button44;
    private java.awt.Button button45;
    private java.awt.Button button46;
    private java.awt.Button button47;
    private java.awt.Button button48;
    private java.awt.Button button49;
    private java.awt.Button button5;
    private java.awt.Button button50;
    private java.awt.Button button51;
    private java.awt.Button button52;
    private java.awt.Button button53;
    private java.awt.Button button54;
    private java.awt.Button button55;
    private java.awt.Button button56;
    private java.awt.Button button57;
    private java.awt.Button button58;
    private java.awt.Button button59;
    private java.awt.Button button6;
    private java.awt.Button button60;
    private java.awt.Button button61;
    private java.awt.Button button62;
    private java.awt.Button button63;
    private java.awt.Button button64;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
