/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package knightstour;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.UIManager;

/**
 *
 * @author PREOATOR
 */
public class Table extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    public Table() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();
        button12 = new java.awt.Button();
        button13 = new java.awt.Button();
        button14 = new java.awt.Button();
        button15 = new java.awt.Button();
        button16 = new java.awt.Button();
        button17 = new java.awt.Button();
        button18 = new java.awt.Button();
        button19 = new java.awt.Button();
        button20 = new java.awt.Button();
        button21 = new java.awt.Button();
        button22 = new java.awt.Button();
        button23 = new java.awt.Button();
        button24 = new java.awt.Button();
        button25 = new java.awt.Button();
        button26 = new java.awt.Button();
        button27 = new java.awt.Button();
        button28 = new java.awt.Button();
        button29 = new java.awt.Button();
        button30 = new java.awt.Button();
        button31 = new java.awt.Button();
        button32 = new java.awt.Button();
        button33 = new java.awt.Button();
        button34 = new java.awt.Button();
        button35 = new java.awt.Button();
        button36 = new java.awt.Button();
        button37 = new java.awt.Button();
        button38 = new java.awt.Button();
        button39 = new java.awt.Button();
        button40 = new java.awt.Button();
        button41 = new java.awt.Button();
        button42 = new java.awt.Button();
        button43 = new java.awt.Button();
        button44 = new java.awt.Button();
        button45 = new java.awt.Button();
        button46 = new java.awt.Button();
        button47 = new java.awt.Button();
        button48 = new java.awt.Button();
        button49 = new java.awt.Button();
        button50 = new java.awt.Button();
        button51 = new java.awt.Button();
        button52 = new java.awt.Button();
        button53 = new java.awt.Button();
        button54 = new java.awt.Button();
        button55 = new java.awt.Button();
        button56 = new java.awt.Button();
        button57 = new java.awt.Button();
        button58 = new java.awt.Button();
        button59 = new java.awt.Button();
        button60 = new java.awt.Button();
        button61 = new java.awt.Button();
        button62 = new java.awt.Button();
        button63 = new java.awt.Button();
        button64 = new java.awt.Button();
        Header = new javax.swing.JPanel();
        WelcomeText = new javax.swing.JLabel();
        MainLogo5 = new javax.swing.JLabel();
        MainLogo7 = new javax.swing.JLabel();
        MainLogo8 = new javax.swing.JLabel();
        MainLogo6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setBackground(new java.awt.Color(255, 255, 255));
        button1.setFocusable(false);
        button1.setName(""); // NOI18N
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 40, 40));

        button2.setBackground(new java.awt.Color(37, 38, 103));
        button2.setFocusable(false);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 40, 40));

        button3.setBackground(new java.awt.Color(255, 255, 255));
        button3.setFocusable(false);
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 40, 40));

        button4.setBackground(new java.awt.Color(37, 38, 103));
        button4.setFocusable(false);
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 40, 40));

        button5.setBackground(new java.awt.Color(255, 255, 255));
        button5.setFocusable(false);
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 40, 40));

        button6.setBackground(new java.awt.Color(37, 38, 103));
        button6.setFocusable(false);
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        getContentPane().add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 40, 40));

        button7.setBackground(new java.awt.Color(255, 255, 255));
        button7.setFocusable(false);
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        getContentPane().add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 40, 40));

        button8.setBackground(new java.awt.Color(37, 38, 103));
        button8.setFocusable(false);
        button8.setName(""); // NOI18N
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        getContentPane().add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 40, 40));

        button9.setActionCommand("1X2");
        button9.setBackground(new java.awt.Color(255, 255, 255));
        button9.setFocusable(false);
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        getContentPane().add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 40, 40));

        button10.setActionCommand("1X3");
        button10.setBackground(new java.awt.Color(37, 38, 103));
        button10.setFocusable(false);
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        getContentPane().add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 40, 40));

        button11.setBackground(new java.awt.Color(255, 255, 255));
        button11.setFocusable(false);
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        getContentPane().add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 40, 40));

        button12.setBackground(new java.awt.Color(37, 38, 103));
        button12.setFocusable(false);
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        getContentPane().add(button12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 40, 40));

        button13.setBackground(new java.awt.Color(255, 255, 255));
        button13.setFocusable(false);
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });
        getContentPane().add(button13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 40, 40));

        button14.setBackground(new java.awt.Color(37, 38, 103));
        button14.setFocusable(false);
        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });
        getContentPane().add(button14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 40, 40));

        button15.setBackground(new java.awt.Color(255, 255, 255));
        button15.setFocusable(false);
        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });
        getContentPane().add(button15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 40, 40));

        button16.setActionCommand("1X1");
        button16.setBackground(new java.awt.Color(37, 38, 103));
        button16.setFocusable(false);
        button16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button16ActionPerformed(evt);
            }
        });
        getContentPane().add(button16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 40, 40));

        button17.setActionCommand("1X2");
        button17.setBackground(new java.awt.Color(37, 38, 103));
        button17.setFocusable(false);
        button17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button17ActionPerformed(evt);
            }
        });
        getContentPane().add(button17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 40, 40));

        button18.setActionCommand("1X3");
        button18.setBackground(new java.awt.Color(255, 255, 255));
        button18.setFocusable(false);
        button18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button18ActionPerformed(evt);
            }
        });
        getContentPane().add(button18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 40, 40));

        button19.setBackground(new java.awt.Color(37, 38, 103));
        button19.setFocusable(false);
        button19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button19ActionPerformed(evt);
            }
        });
        getContentPane().add(button19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 40, 40));

        button20.setBackground(new java.awt.Color(255, 255, 255));
        button20.setFocusable(false);
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });
        getContentPane().add(button20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 40, 40));

        button21.setBackground(new java.awt.Color(37, 38, 103));
        button21.setFocusable(false);
        button21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button21ActionPerformed(evt);
            }
        });
        getContentPane().add(button21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 40, 40));

        button22.setBackground(new java.awt.Color(255, 255, 255));
        button22.setFocusable(false);
        button22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button22ActionPerformed(evt);
            }
        });
        getContentPane().add(button22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 40, 40));

        button23.setBackground(new java.awt.Color(37, 38, 103));
        button23.setFocusable(false);
        button23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button23ActionPerformed(evt);
            }
        });
        getContentPane().add(button23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 40, 40));

        button24.setActionCommand("1X1");
        button24.setBackground(new java.awt.Color(255, 255, 255));
        button24.setFocusable(false);
        button24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button24ActionPerformed(evt);
            }
        });
        getContentPane().add(button24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 40, 40));

        button25.setActionCommand("1X2");
        button25.setBackground(new java.awt.Color(255, 255, 255));
        button25.setFocusable(false);
        button25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button25ActionPerformed(evt);
            }
        });
        getContentPane().add(button25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 40, 40));

        button26.setActionCommand("1X3");
        button26.setBackground(new java.awt.Color(37, 38, 103));
        button26.setFocusable(false);
        button26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button26ActionPerformed(evt);
            }
        });
        getContentPane().add(button26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 40, 40));

        button27.setBackground(new java.awt.Color(255, 255, 255));
        button27.setFocusable(false);
        button27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button27ActionPerformed(evt);
            }
        });
        getContentPane().add(button27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 40, 40));

        button28.setBackground(new java.awt.Color(37, 38, 103));
        button28.setFocusable(false);
        button28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button28ActionPerformed(evt);
            }
        });
        getContentPane().add(button28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 40, 40));

        button29.setBackground(new java.awt.Color(255, 255, 255));
        button29.setFocusable(false);
        button29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button29ActionPerformed(evt);
            }
        });
        getContentPane().add(button29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 40, 40));

        button30.setBackground(new java.awt.Color(37, 38, 103));
        button30.setFocusable(false);
        button30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button30ActionPerformed(evt);
            }
        });
        getContentPane().add(button30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 40, 40));

        button31.setBackground(new java.awt.Color(255, 255, 255));
        button31.setFocusable(false);
        button31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button31ActionPerformed(evt);
            }
        });
        getContentPane().add(button31, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 40, 40));

        button32.setActionCommand("1X1");
        button32.setBackground(new java.awt.Color(37, 38, 103));
        button32.setFocusable(false);
        button32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button32ActionPerformed(evt);
            }
        });
        getContentPane().add(button32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 40, 40));

        button33.setActionCommand("1X2");
        button33.setBackground(new java.awt.Color(37, 38, 103));
        button33.setFocusable(false);
        button33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button33ActionPerformed(evt);
            }
        });
        getContentPane().add(button33, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 40, 40));

        button34.setActionCommand("1X3");
        button34.setBackground(new java.awt.Color(255, 255, 255));
        button34.setFocusable(false);
        button34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button34ActionPerformed(evt);
            }
        });
        getContentPane().add(button34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 40, 40));

        button35.setBackground(new java.awt.Color(37, 38, 103));
        button35.setFocusable(false);
        button35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button35ActionPerformed(evt);
            }
        });
        getContentPane().add(button35, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 40, 40));

        button36.setBackground(new java.awt.Color(255, 255, 255));
        button36.setFocusable(false);
        button36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button36ActionPerformed(evt);
            }
        });
        getContentPane().add(button36, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 40, 40));

        button37.setBackground(new java.awt.Color(37, 38, 103));
        button37.setFocusable(false);
        button37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button37ActionPerformed(evt);
            }
        });
        getContentPane().add(button37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 40, 40));

        button38.setBackground(new java.awt.Color(255, 255, 255));
        button38.setFocusable(false);
        button38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button38ActionPerformed(evt);
            }
        });
        getContentPane().add(button38, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 40, 40));

        button39.setBackground(new java.awt.Color(37, 38, 103));
        button39.setFocusable(false);
        button39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button39ActionPerformed(evt);
            }
        });
        getContentPane().add(button39, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 40, 40));

        button40.setActionCommand("1X1");
        button40.setBackground(new java.awt.Color(255, 255, 255));
        button40.setFocusable(false);
        button40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button40ActionPerformed(evt);
            }
        });
        getContentPane().add(button40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 40, 40));

        button41.setActionCommand("1X2");
        button41.setBackground(new java.awt.Color(255, 255, 255));
        button41.setFocusable(false);
        button41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button41ActionPerformed(evt);
            }
        });
        getContentPane().add(button41, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 40, 40));

        button42.setActionCommand("1X3");
        button42.setBackground(new java.awt.Color(37, 38, 103));
        button42.setFocusable(false);
        button42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button42ActionPerformed(evt);
            }
        });
        getContentPane().add(button42, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 40, 40));

        button43.setBackground(new java.awt.Color(255, 255, 255));
        button43.setFocusable(false);
        button43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button43ActionPerformed(evt);
            }
        });
        getContentPane().add(button43, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 40, 40));

        button44.setBackground(new java.awt.Color(37, 38, 103));
        button44.setFocusable(false);
        button44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button44ActionPerformed(evt);
            }
        });
        getContentPane().add(button44, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 40, 40));

        button45.setBackground(new java.awt.Color(255, 255, 255));
        button45.setFocusable(false);
        button45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button45ActionPerformed(evt);
            }
        });
        getContentPane().add(button45, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 40, 40));

        button46.setBackground(new java.awt.Color(37, 38, 103));
        button46.setFocusable(false);
        button46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button46ActionPerformed(evt);
            }
        });
        getContentPane().add(button46, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 40, 40));

        button47.setBackground(new java.awt.Color(255, 255, 255));
        button47.setFocusable(false);
        button47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button47ActionPerformed(evt);
            }
        });
        getContentPane().add(button47, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 40, 40));

        button48.setActionCommand("1X1");
        button48.setBackground(new java.awt.Color(37, 38, 103));
        button48.setFocusable(false);
        button48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button48ActionPerformed(evt);
            }
        });
        getContentPane().add(button48, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 40, 40));

        button49.setActionCommand("1X2");
        button49.setBackground(new java.awt.Color(37, 38, 103));
        button49.setFocusable(false);
        button49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button49ActionPerformed(evt);
            }
        });
        getContentPane().add(button49, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 40, 40));

        button50.setActionCommand("1X3");
        button50.setBackground(new java.awt.Color(255, 255, 255));
        button50.setFocusable(false);
        button50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button50ActionPerformed(evt);
            }
        });
        getContentPane().add(button50, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 40, 40));

        button51.setBackground(new java.awt.Color(37, 38, 103));
        button51.setFocusable(false);
        button51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button51ActionPerformed(evt);
            }
        });
        getContentPane().add(button51, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 40, 40));

        button52.setBackground(new java.awt.Color(255, 255, 255));
        button52.setFocusable(false);
        button52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button52ActionPerformed(evt);
            }
        });
        getContentPane().add(button52, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 40, 40));

        button53.setBackground(new java.awt.Color(37, 38, 103));
        button53.setFocusable(false);
        button53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button53ActionPerformed(evt);
            }
        });
        getContentPane().add(button53, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 40, 40));

        button54.setBackground(new java.awt.Color(255, 255, 255));
        button54.setFocusable(false);
        button54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button54ActionPerformed(evt);
            }
        });
        getContentPane().add(button54, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 40, 40));

        button55.setBackground(new java.awt.Color(37, 38, 103));
        button55.setFocusable(false);
        button55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button55ActionPerformed(evt);
            }
        });
        getContentPane().add(button55, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 40, 40));

        button56.setActionCommand("1X1");
        button56.setBackground(new java.awt.Color(255, 255, 255));
        button56.setFocusable(false);
        button56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button56ActionPerformed(evt);
            }
        });
        getContentPane().add(button56, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 40, 40));

        button57.setActionCommand("1X2");
        button57.setBackground(new java.awt.Color(255, 255, 255));
        button57.setFocusable(false);
        button57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button57ActionPerformed(evt);
            }
        });
        getContentPane().add(button57, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 40, 40));

        button58.setActionCommand("1X3");
        button58.setBackground(new java.awt.Color(37, 38, 103));
        button58.setFocusable(false);
        button58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button58ActionPerformed(evt);
            }
        });
        getContentPane().add(button58, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 40, 40));

        button59.setBackground(new java.awt.Color(255, 255, 255));
        button59.setFocusable(false);
        button59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button59ActionPerformed(evt);
            }
        });
        getContentPane().add(button59, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 40, 40));

        button60.setBackground(new java.awt.Color(37, 38, 103));
        button60.setFocusable(false);
        button60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button60ActionPerformed(evt);
            }
        });
        getContentPane().add(button60, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 40, 40));

        button61.setBackground(new java.awt.Color(255, 255, 255));
        button61.setFocusable(false);
        button61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button61ActionPerformed(evt);
            }
        });
        getContentPane().add(button61, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 40, 40));

        button62.setBackground(new java.awt.Color(37, 38, 103));
        button62.setFocusable(false);
        button62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button62ActionPerformed(evt);
            }
        });
        getContentPane().add(button62, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 40, 40));

        button63.setBackground(new java.awt.Color(255, 255, 255));
        button63.setFocusable(false);
        button63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button63ActionPerformed(evt);
            }
        });
        getContentPane().add(button63, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 40, 40));

        button64.setActionCommand("1X1");
        button64.setBackground(new java.awt.Color(37, 38, 103));
        button64.setFocusable(false);
        button64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button64ActionPerformed(evt);
            }
        });
        getContentPane().add(button64, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 40, 40));

        Header.setBackground(new java.awt.Color(37, 38, 103));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        WelcomeText.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(WelcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 20, 40));

        MainLogo5.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo5.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(MainLogo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 20, 20));

        MainLogo7.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo7.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(MainLogo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 20, 20));

        MainLogo8.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo8.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(MainLogo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 20, 20));

        MainLogo6.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo6.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(MainLogo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 280, 20));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 8)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("About");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("© 2018 Knight's Tour Solver, All rights reserved.");
        Header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 30));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 480, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/knightstour/table.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 420, 430));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/knightstour/header.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 420, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        PathTable p = new PathTable(0, 0, this);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        PathTable p = new PathTable(0, 1, this);
    }//GEN-LAST:event_button2ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        PathTable p = new PathTable(0, 3, this);
    }//GEN-LAST:event_button4ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        PathTable p = new PathTable(0, 5, this);
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        PathTable p = new PathTable(0, 6, this);
    }//GEN-LAST:event_button7ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        PathTable p = new PathTable(1, 1, this);
    }//GEN-LAST:event_button9ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        PathTable p = new PathTable(1, 3, this);
    }//GEN-LAST:event_button11ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
        PathTable p = new PathTable(1, 5, this);
    }//GEN-LAST:event_button13ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
        PathTable p = new PathTable(1, 6, this);
    }//GEN-LAST:event_button14ActionPerformed

    private void button16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button16ActionPerformed
        PathTable p = new PathTable(1, 0, this);
    }//GEN-LAST:event_button16ActionPerformed

    private void button17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button17ActionPerformed
        PathTable p = new PathTable(2, 1, this);
    }//GEN-LAST:event_button17ActionPerformed

    private void button19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button19ActionPerformed
        PathTable p = new PathTable(2, 3, this);
    }//GEN-LAST:event_button19ActionPerformed

    private void button21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button21ActionPerformed
        PathTable p = new PathTable(2, 5, this);
    }//GEN-LAST:event_button21ActionPerformed

    private void button22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button22ActionPerformed
        PathTable p = new PathTable(2, 6, this);
    }//GEN-LAST:event_button22ActionPerformed

    private void button24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button24ActionPerformed
        PathTable p = new PathTable(2, 0, this);
    }//GEN-LAST:event_button24ActionPerformed

    private void button25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button25ActionPerformed
        PathTable p = new PathTable(3, 1, this);
    }//GEN-LAST:event_button25ActionPerformed

    private void button27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button27ActionPerformed
        PathTable p = new PathTable(3, 3, this);
    }//GEN-LAST:event_button27ActionPerformed

    private void button29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button29ActionPerformed
        PathTable p = new PathTable(3, 5, this);
    }//GEN-LAST:event_button29ActionPerformed

    private void button30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button30ActionPerformed
        PathTable p = new PathTable(3, 6, this);
    }//GEN-LAST:event_button30ActionPerformed

    private void button32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button32ActionPerformed
        PathTable p = new PathTable(3, 0, this);
    }//GEN-LAST:event_button32ActionPerformed

    private void button33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button33ActionPerformed
        PathTable p = new PathTable(4, 1, this);
    }//GEN-LAST:event_button33ActionPerformed

    private void button35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button35ActionPerformed
        PathTable p = new PathTable(4, 3, this);
    }//GEN-LAST:event_button35ActionPerformed

    private void button37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button37ActionPerformed
        PathTable p = new PathTable(4, 5, this);
    }//GEN-LAST:event_button37ActionPerformed

    private void button38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button38ActionPerformed
        PathTable p = new PathTable(4, 6, this);
    }//GEN-LAST:event_button38ActionPerformed

    private void button40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button40ActionPerformed
        PathTable p = new PathTable(4, 0, this);
    }//GEN-LAST:event_button40ActionPerformed

    private void button41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button41ActionPerformed
        PathTable p = new PathTable(5, 1, this);
    }//GEN-LAST:event_button41ActionPerformed

    private void button43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button43ActionPerformed
        PathTable p = new PathTable(5, 3, this);
    }//GEN-LAST:event_button43ActionPerformed

    private void button45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button45ActionPerformed
        PathTable p = new PathTable(5, 5, this);
    }//GEN-LAST:event_button45ActionPerformed

    private void button46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button46ActionPerformed
        PathTable p = new PathTable(5, 6, this);
    }//GEN-LAST:event_button46ActionPerformed

    private void button48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button48ActionPerformed
        PathTable p = new PathTable(5, 0, this);
    }//GEN-LAST:event_button48ActionPerformed

    private void button49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button49ActionPerformed
        PathTable p = new PathTable(6, 1, this);
    }//GEN-LAST:event_button49ActionPerformed

    private void button51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button51ActionPerformed
        PathTable p = new PathTable(6, 3, this);
    }//GEN-LAST:event_button51ActionPerformed

    private void button53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button53ActionPerformed
        PathTable p = new PathTable(6, 5, this);
    }//GEN-LAST:event_button53ActionPerformed

    private void button54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button54ActionPerformed
        PathTable p = new PathTable(6, 6, this);
    }//GEN-LAST:event_button54ActionPerformed

    private void button56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button56ActionPerformed
        PathTable p = new PathTable(6, 0, this);
    }//GEN-LAST:event_button56ActionPerformed

    private void button57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button57ActionPerformed
        PathTable p = new PathTable(7, 1, this);
    }//GEN-LAST:event_button57ActionPerformed

    private void button59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button59ActionPerformed
        PathTable p = new PathTable(7, 3, this);
    }//GEN-LAST:event_button59ActionPerformed

    private void button61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button61ActionPerformed
        PathTable p = new PathTable(7, 5, this);
    }//GEN-LAST:event_button61ActionPerformed

    private void button62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button62ActionPerformed
        PathTable p = new PathTable(7, 6, this);
    }//GEN-LAST:event_button62ActionPerformed

    private void button64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button64ActionPerformed
        PathTable p = new PathTable(7, 0, this);
    }//GEN-LAST:event_button64ActionPerformed

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseClicked

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        PathTable p = new PathTable(0, 4, this);
    }//GEN-LAST:event_button5ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        PathTable p = new PathTable(0, 2, this);
    }//GEN-LAST:event_button3ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        PathTable p = new PathTable(0, 7, this);
    }//GEN-LAST:event_button8ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        PathTable p = new PathTable(1, 2, this);
    }//GEN-LAST:event_button10ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        PathTable p = new PathTable(1, 4, this);
    }//GEN-LAST:event_button12ActionPerformed

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
        PathTable p = new PathTable(1, 7, this);
    }//GEN-LAST:event_button15ActionPerformed

    private void button18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button18ActionPerformed
        PathTable p = new PathTable(2, 2, this);
    }//GEN-LAST:event_button18ActionPerformed

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20ActionPerformed
        PathTable p = new PathTable(2, 4, this);
    }//GEN-LAST:event_button20ActionPerformed

    private void button23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button23ActionPerformed
        PathTable p = new PathTable(2, 7, this);
    }//GEN-LAST:event_button23ActionPerformed

    private void button26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button26ActionPerformed
        PathTable p = new PathTable(3, 2, this);
    }//GEN-LAST:event_button26ActionPerformed

    private void button28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button28ActionPerformed
        PathTable p = new PathTable(3, 4, this);
    }//GEN-LAST:event_button28ActionPerformed

    private void button31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button31ActionPerformed
        PathTable p = new PathTable(3, 7, this);
    }//GEN-LAST:event_button31ActionPerformed

    private void button34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button34ActionPerformed
        PathTable p = new PathTable(4, 2, this);
    }//GEN-LAST:event_button34ActionPerformed

    private void button36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button36ActionPerformed
        PathTable p = new PathTable(4, 4, this);
    }//GEN-LAST:event_button36ActionPerformed

    private void button39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button39ActionPerformed
        PathTable p = new PathTable(4, 7, this);
    }//GEN-LAST:event_button39ActionPerformed

    private void button42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button42ActionPerformed
        PathTable p = new PathTable(5, 2, this);
    }//GEN-LAST:event_button42ActionPerformed

    private void button44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button44ActionPerformed
        PathTable p = new PathTable(5, 4, this);
    }//GEN-LAST:event_button44ActionPerformed

    private void button47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button47ActionPerformed
        PathTable p = new PathTable(5, 7, this);
    }//GEN-LAST:event_button47ActionPerformed

    private void button50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button50ActionPerformed
        PathTable p = new PathTable(6, 2, this);
    }//GEN-LAST:event_button50ActionPerformed

    private void button52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button52ActionPerformed
        PathTable p = new PathTable(6, 4, this);
    }//GEN-LAST:event_button52ActionPerformed

    private void button55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button55ActionPerformed
        PathTable p = new PathTable(6, 0, this);
    }//GEN-LAST:event_button55ActionPerformed

    private void button58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button58ActionPerformed
        PathTable p = new PathTable(7, 2, this);
    }//GEN-LAST:event_button58ActionPerformed

    private void button60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button60ActionPerformed
        PathTable p = new PathTable(7, 4, this);
    }//GEN-LAST:event_button60ActionPerformed

    private void button63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button63ActionPerformed
        PathTable p = new PathTable(7, 7, this);
    }//GEN-LAST:event_button63ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new About().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel MainLogo5;
    private javax.swing.JLabel MainLogo6;
    private javax.swing.JLabel MainLogo7;
    private javax.swing.JLabel MainLogo8;
    private javax.swing.JLabel WelcomeText;
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button button14;
    private java.awt.Button button15;
    private java.awt.Button button16;
    private java.awt.Button button17;
    private java.awt.Button button18;
    private java.awt.Button button19;
    private java.awt.Button button2;
    private java.awt.Button button20;
    private java.awt.Button button21;
    private java.awt.Button button22;
    private java.awt.Button button23;
    private java.awt.Button button24;
    private java.awt.Button button25;
    private java.awt.Button button26;
    private java.awt.Button button27;
    private java.awt.Button button28;
    private java.awt.Button button29;
    private java.awt.Button button3;
    private java.awt.Button button30;
    private java.awt.Button button31;
    private java.awt.Button button32;
    private java.awt.Button button33;
    private java.awt.Button button34;
    private java.awt.Button button35;
    private java.awt.Button button36;
    private java.awt.Button button37;
    private java.awt.Button button38;
    private java.awt.Button button39;
    private java.awt.Button button4;
    private java.awt.Button button40;
    private java.awt.Button button41;
    private java.awt.Button button42;
    private java.awt.Button button43;
    private java.awt.Button button44;
    private java.awt.Button button45;
    private java.awt.Button button46;
    private java.awt.Button button47;
    private java.awt.Button button48;
    private java.awt.Button button49;
    private java.awt.Button button5;
    private java.awt.Button button50;
    private java.awt.Button button51;
    private java.awt.Button button52;
    private java.awt.Button button53;
    private java.awt.Button button54;
    private java.awt.Button button55;
    private java.awt.Button button56;
    private java.awt.Button button57;
    private java.awt.Button button58;
    private java.awt.Button button59;
    private java.awt.Button button6;
    private java.awt.Button button60;
    private java.awt.Button button61;
    private java.awt.Button button62;
    private java.awt.Button button63;
    private java.awt.Button button64;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
